### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kildom** [kildom/cre-web-demo#1]
* [ ] update to newest node modules
* [ ] add source code (in compressed and encoded form) in the address bar. Compression experiments in a different branch. It should also contains file name.
* [ ] add browser storage
* [ ] add multiple files support (in tabs)
* [ ] add sharing button that copies the address
* [ ] show "View as HTML" check box if HTML is detected in the output.
* [ ] add Open button with menu: sample files (title as label), tutorial files (section and stage as label), recently closed files (modification time as label), from URL. File will not be saved as "recently closed" if it is identical to sample or tutorial.
* [ ] Download file button
* [ ] Use [compression api](https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API) if available or WASM zstd. The `zstd --train` command allows to create custom dictionary. Looks like fflake does not provide good compression level.

Apply to web demo and VCS plugin:
* [ ] use registerDocumentSemanticTokensProvider to do coloring of the CRE.
* [ ] use [codelens](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#example-extending-language-services-codelens-provider-example) to automatically generate interfaces in TypeScript (only VSC). May be not 100% accurate because of interpolation - simple solution: allow user to handle interpolation, e.g. by allowing to add `extends` in the generated interface. Alternative: use model-markers below.
* [ ] use [completion-provider](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#example-extending-language-services-completion-provider-example) for autocomplete CRE
* [ ] use [configure-javascript-defaults](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#example-extending-language-services-configure-javascript-defaults) to provide declarations for cre if possible (only in web demo)
* [ ] use [hover-provider](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#example-extending-language-services-hover-provider-example) to explain each token in the CRE. Hovering the `cre` should show the compiled expression if interpolation allows it.
* [ ] use [model-markers](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#example-extending-language-services-model-markers-example) to show errors and warnings in the CRE. Second usage in typescript: use it to mark `/*# interface myGroupInterface */ if the interface is out of date allowing to regenerate if needed.

[registerDocumentSemanticTokensProvider sample code with CRE](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#XQAAAAJtEwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxegDitIojQCQ435HMWrcEAUNQfCKcfdrxNgdYpW-T681WSm7f61Y_VnExj9qIloViVCI-I2KMKeO_o26zbOharDbpYKGfi30KJHWQMugI9kJmhX8JZKSBh5KlMiLcZqBjZN86KxzxFKT-GaY0rywov86lGTKBWiZo5o6CphlEHYxSyb95NKBUDvKMCPlusKQAZdCHNXThzuODeadsqMmaKhtnHV12mQCVg9SN-Thn9wg0mR93AUfyyG4q6hABB8F8RjsDX9vTtWtUnbDOatRva5jO3r4Tvdgi-gv04eSKhZPpC7rpWFJa61N-tyqtcoZZnih4_XmQwmJ3dROozzqJbO3oXQOmehfBbM3VkOxoaotVEbqrsyHuzmAvVx0xp6thAuowaPCcZhMbLnMF-jHEAsUesEfoUfnnreY2E7C7UrP3sQ1BsXcQI-Tci4ABojaSDNQ66K3cOrOzUo-e4eplextvDAte_zBpdocPswVgIay1UFXHXy1WW30TIY68FX-4hxPdfsRYR4YY5ja-qV2whrpZW5PASduvX9KDR-ouJu3bO36r3nUEOtkODMy2kulk5_niKOQt-oqz9bIgPVz2-i7sdMyiokuVhnsSHe3Q2937Mja6yh9-0eXHLserGGRfhqc2CweUPeNGRU-Ui9VpGdTDQvIb6zaAE1NBeU5qeIMhHdfB0YtG1_pW8hB2tg6_73wiEzB6UYxkGQQ2RJmqCg0VHZsYHSxPAXxy72rUSFds45_7m_6Xf0JI0ypyrLIcKJQ_jTTK1pvaYcb9bMgRcL8lo4I6lsUC8dwcGylw8Bv9HHnxS4CqXJperS9r7c5VyHP6GENQvDFjTw9bZxt5ssxrOniRw9-anB2Y7uy_e4DeZF-gnJBr9q3Q0BL_Ftg392lb-zGDXnSb5SpxZHcRKJCWBPJzULH1pFw-5IVIQ5vKtQIb1mZajeBqn_iKXnqzcB-PfnitXOaC1ljq5mgVmswOlw5JMHu6raJIW7808_kHs_EO-GokOe1hWbGeJYBIkUldb_NBw8mw0Bho8AxbVJpBGbb7EV10o9jUWfN97SpuRJ8zQAu5gRqbXC1jykPEQN93We1fO93R-_ECi-zb8RECmBWHgnla8gDkOf9WP1xob6oNDDgnaPdV4AEZegc_yVcEYuy9yQPTgpF93zK1XbY4Or95uVTNtWaxLDZnFdYIc32MIaVLfFfghjanpoEfG7IUNDmPoJzua9DPqO08iuj61nu1WVICbdCIb2bAQZ9tGg2V0ocLEjuIOCve5rBUs5YzirKIVE-2FKcumBb6oAy8wZiXi3PWc-yAWxDLONbUHwiZ1WkPzcWEs03Dm5fJg-1UlhUfoLrMCE_imDmSdXKnrYNQ5WC2nr1VLJc3Ki6YLgwH0sNlRtSW99WowWp7-fmGUJ0z9VhcO9MTPIioW40og13zUsAh4usjy2fkwP3KxkYE1RA0mKFC9KueQdhzlwOoKOryLv7g-82b2qwYTMnE4FBaFdt0KqD3cvB8dOPUIjdcknWLwrz_mh4VxPGCzYSD795eEJvgOKElOHGOT5je7_VzibpF0OpgAdXPOV8dfSZKdYEeqSMYBwEL-mDVsMvlaNYdNgic7WJocCJq-qNsjnNS0-J-7FDwlqQ9oH_cHWOdzg51VaoL2LO5rUKgbQDqyh8ss7S3NFCfgzUnJ8-927ZnAGTyFYOF1zNJ5qo6DYifW57HovlDyZoN8v1i8UjvmjOJqm7PvqRzbajhBpKAZFLwBcPTKTna2Zjio3jT6kT-iFXu4apQhDwXnA2uvwlxpFmhuIkR1Bf1mboSlU4aGihGOwgwNSPS4Gf-7bAmVceKcUY_kVM5_7O82l1LKPKS7r_qFbGiaUfOx2xqYxteIQChqdzA8Xvi1KXTPSdlxbToLzwXJenigfRSBOLyk-M_bCZnaTixEYFIJTNi4D9uMTGo7zvgejJpFiQO8YPUSs4KSbOrnlpYqWqDeVBbgHGwBDY38cIDP-W5Fp2TgoY_M8qhzApH00rhzVGOdeby85wPhdXG5unXjiNj23soLHSM7y_1lnDWKR8o9R61gsnBY572qL_XmBOfqPTTQMkgyoMaycII9vbCrsBd0YcYw5UqU-rWfUlTJ0LXjXk4VGxwEHWmSOURvWU5j4YiTybjPhJkvgiVQySMXl3Xv3FX_jFqejyTrhkymEkTDnyMwWjZkJDp8RAkQcgjLp3LicxdZcNgypm7etnNPs3Ob6hqHH6SHS-ld-OzDz58M89we-JDxr2OixOyr5y1d0sySUP-ghiXC4lADLUUddqrGBE-Hvcrb5-cOaP_gn3rAA)

https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide
